name: Autograding Tests
on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    container: stellargroup/pintos:latest

    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # This is where you place your autograding tests
    # For more information on this runner, see the documentation at: 
    # https://github.com/classroom-resources/autograding-command-grader
    - name: Run User Program Tests
      uses: classroom-resources/autograding-command-grader@v1
      id: userprog
      with:
        test-name: User Program Tests
        setup-command: cd src/userprog; make
        command: cd src/userprog; make -i check grade
        timeout: 10
        max-score: '100'

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      id: upload
      with:
        name: test-results
        path: |
          src/userprog/build/grade
          src/userprog/build/results

    - name: Report Grading Results
      id: report
      run: |
        cat src/userprog/build/grade.report
        echo 'Detailed test results can be downloaded here: ${{steps.upload.outputs.artifact-url}}'
        exit `cat src/userprog/build/grade.result`
